"""Add integration_accounts table

Revision ID: 35ed6c183ffd
Revises: a8ea415ad0f1
Create Date: 2025-12-23 18:51:09.800528

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '35ed6c183ffd'
down_revision = 'a8ea415ad0f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('integration_accounts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('provider', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('access_token_encrypted', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('refresh_token_encrypted', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('token_expires_at', sa.DateTime(), nullable=False),
    sa.Column('account_email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_integration_accounts_user_id'), 'integration_accounts', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_integration_accounts_user_id'), table_name='integration_accounts')
    op.drop_table('integration_accounts')
    # ### end Alembic commands ###
