"""Add job_runs table

Revision ID: 3f4825412d10
Revises: a1b2c3d4e5f6
Create Date: 2025-12-23 17:43:44.320564

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3f4825412d10'
down_revision = 'a1b2c3d4e5f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('job_type', sa.Enum('AUDIT', 'GSC_SYNC', 'GSC_BACKFILL', 'SERP_REFRESH', 'LINKS_INGEST', 'ADS_SYNC', name='jobtype'), nullable=False),
    sa.Column('celery_task_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Enum('QUEUED', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', name='jobstatus'), nullable=False),
    sa.Column('progress_pct', sa.Integer(), nullable=False),
    sa.Column('progress_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('queued_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('result_json', sa.JSON(), nullable=True),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('config_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_runs_project_id'), 'job_runs', ['project_id'], unique=False)
    op.alter_column('projects', 'settings',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.drop_constraint(op.f('projects_created_by_id_fkey'), 'projects', type_='foreignkey')
    op.create_foreign_key(None, 'projects', 'user', ['created_by_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.create_foreign_key(op.f('projects_created_by_id_fkey'), 'projects', 'user', ['created_by_id'], ['id'], ondelete='CASCADE')
    op.alter_column('projects', 'settings',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.drop_index(op.f('ix_job_runs_project_id'), table_name='job_runs')
    op.drop_table('job_runs')
    # ### end Alembic commands ###
