"""Add SERP tracking models

Revision ID: 7636c6b0b181
Revises: 35ed6c183ffd
Create Date: 2025-12-23 19:36:27.615377

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '7636c6b0b181'
down_revision = '35ed6c183ffd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('keyword_targets',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('keyword', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('locale', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('device', sa.Enum('DESKTOP', 'MOBILE', 'TABLET', name='devicetype'), nullable=False),
    sa.Column('search_engine', sa.Enum('GOOGLE', 'BING', name='searchengine'), nullable=False),
    sa.Column('provider_key', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('refresh_frequency_hours', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('latest_position', sa.Integer(), nullable=True),
    sa.Column('position_change', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('last_refresh_at', sa.DateTime(), nullable=True),
    sa.Column('last_refresh_status', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_keyword_targets_project_id'), 'keyword_targets', ['project_id'], unique=False)
    op.create_table('rank_observations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('keyword_target_id', sa.Uuid(), nullable=False),
    sa.Column('observed_at', sa.DateTime(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(length=2048), nullable=True),
    sa.Column('domain', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('snippet', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'SUCCESS', 'FAILED', 'RATE_LIMITED', name='refreshstatus'), nullable=False),
    sa.ForeignKeyConstraint(['keyword_target_id'], ['keyword_targets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rank_observations_keyword_target_id'), 'rank_observations', ['keyword_target_id'], unique=False)
    op.create_index(op.f('ix_rank_observations_observed_at'), 'rank_observations', ['observed_at'], unique=False)
    op.create_table('serp_snapshots',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('keyword_target_id', sa.Uuid(), nullable=False),
    sa.Column('captured_at', sa.DateTime(), nullable=False),
    sa.Column('results_json', sa.JSON(), nullable=True),
    sa.Column('total_results', sa.Integer(), nullable=True),
    sa.Column('raw_response', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['keyword_target_id'], ['keyword_targets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_serp_snapshots_keyword_target_id'), 'serp_snapshots', ['keyword_target_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_serp_snapshots_keyword_target_id'), table_name='serp_snapshots')
    op.drop_table('serp_snapshots')
    op.drop_index(op.f('ix_rank_observations_observed_at'), table_name='rank_observations')
    op.drop_index(op.f('ix_rank_observations_keyword_target_id'), table_name='rank_observations')
    op.drop_table('rank_observations')
    op.drop_index(op.f('ix_keyword_targets_project_id'), table_name='keyword_targets')
    op.drop_table('keyword_targets')
    # ### end Alembic commands ###
