"""Add audit tables

Revision ID: 77044cb88c57
Revises: a7181391766e
Create Date: 2025-12-23 18:13:33.481609

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '77044cb88c57'
down_revision = 'a7181391766e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'CRAWLING', 'RENDERING', 'ANALYZING', 'DIFFING', 'COMPLETED', 'FAILED', name='auditstatus'), nullable=False),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('stats', sa.JSON(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=True),
    sa.Column('progress_pct', sa.Float(), nullable=False),
    sa.Column('progress_message', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_issues',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('audit_run_id', sa.Uuid(), nullable=False),
    sa.Column('page_url', sqlmodel.sql.sqltypes.AutoString(length=2048), nullable=False),
    sa.Column('issue_type', sa.Enum('SERVER_ERROR_5XX', 'REDIRECT_LOOP', 'REDIRECT_CHAIN', 'BROKEN_INTERNAL_LINK', 'CLIENT_ERROR_4XX', 'MISSING_TITLE', 'DUPLICATE_TITLE', 'MISSING_META_DESCRIPTION', 'TITLE_TOO_LONG', 'TITLE_TOO_SHORT', 'META_DESC_TOO_LONG', 'META_DESC_TOO_SHORT', 'MISSING_H1', 'MULTIPLE_H1', 'MISSING_CANONICAL', 'CANONICAL_MISMATCH', 'NON_HTTPS', 'THIN_CONTENT', 'ORPHAN_PAGE', name='issuetype'), nullable=False),
    sa.Column('severity', sa.Enum('CRITICAL', 'HIGH', 'MEDIUM', 'LOW', name='issueseverity'), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('first_seen_run_id', sa.Uuid(), nullable=True),
    sa.Column('is_new', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['audit_run_id'], ['audit_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['first_seen_run_id'], ['audit_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_issues_page_url'), 'audit_issues', ['page_url'], unique=False)
    op.create_table('audit_link_edges',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('audit_run_id', sa.Uuid(), nullable=False),
    sa.Column('source_url', sqlmodel.sql.sqltypes.AutoString(length=2048), nullable=False),
    sa.Column('target_url', sqlmodel.sql.sqltypes.AutoString(length=2048), nullable=False),
    sa.Column('anchor_text', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('is_internal', sa.Boolean(), nullable=False),
    sa.Column('is_followed', sa.Boolean(), nullable=False),
    sa.Column('target_status_code', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['audit_run_id'], ['audit_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_link_edges_source_url'), 'audit_link_edges', ['source_url'], unique=False)
    op.create_index(op.f('ix_audit_link_edges_target_url'), 'audit_link_edges', ['target_url'], unique=False)
    op.create_table('crawled_pages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('audit_run_id', sa.Uuid(), nullable=False),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(length=2048), nullable=False),
    sa.Column('final_url', sqlmodel.sql.sqltypes.AutoString(length=2048), nullable=False),
    sa.Column('depth', sa.Integer(), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('content_type', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('response_time_ms', sa.Integer(), nullable=True),
    sa.Column('redirect_chain', sa.JSON(), nullable=True),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('meta_description', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=True),
    sa.Column('canonical', sqlmodel.sql.sqltypes.AutoString(length=2048), nullable=True),
    sa.Column('h1_count', sa.Integer(), nullable=True),
    sa.Column('first_h1', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('word_count', sa.Integer(), nullable=True),
    sa.Column('meta_robots', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('is_rendered', sa.Boolean(), nullable=False),
    sa.Column('rendered_at', sa.DateTime(), nullable=True),
    sa.Column('rendered_title', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('rendered_meta_description', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=True),
    sa.Column('rendered_h1_count', sa.Integer(), nullable=True),
    sa.Column('rendered_word_count', sa.Integer(), nullable=True),
    sa.Column('content_hash', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('crawled_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['audit_run_id'], ['audit_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crawled_pages_url'), 'crawled_pages', ['url'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_crawled_pages_url'), table_name='crawled_pages')
    op.drop_table('crawled_pages')
    op.drop_index(op.f('ix_audit_link_edges_target_url'), table_name='audit_link_edges')
    op.drop_index(op.f('ix_audit_link_edges_source_url'), table_name='audit_link_edges')
    op.drop_table('audit_link_edges')
    op.drop_index(op.f('ix_audit_issues_page_url'), table_name='audit_issues')
    op.drop_table('audit_issues')
    op.drop_table('audit_runs')
    # ### end Alembic commands ###
