"""add_traffic_daily_table

Revision ID: 8c79742360e6
Revises: b6b47410d782
Create Date: 2025-12-24 00:16:03.247343

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '8c79742360e6'
down_revision = 'b6b47410d782'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transparency_creatives',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source_key', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('advertiser_id', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('advertiser_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('creative_id', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('headline', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=False),
    sa.Column('image_url', sqlmodel.sql.sqltypes.AutoString(length=2048), nullable=True),
    sa.Column('landing_url', sqlmodel.sql.sqltypes.AutoString(length=2048), nullable=True),
    sa.Column('first_seen', sa.Date(), nullable=False),
    sa.Column('last_seen', sa.Date(), nullable=False),
    sa.Column('geo_targeting', sa.JSON(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_transparency_advertiser', 'transparency_creatives', ['advertiser_id'], unique=False)
    op.create_index(op.f('ix_transparency_creatives_advertiser_id'), 'transparency_creatives', ['advertiser_id'], unique=False)
    op.create_table('ads_accounts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('customer_id', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('descriptive_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('currency_code', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('linked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sync_status', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ads_accounts_project_id'), 'ads_accounts', ['project_id'], unique=True)
    op.create_table('ads_campaign_daily',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('campaign_id', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('campaign_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('campaign_status', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('impressions', sa.Integer(), nullable=False),
    sa.Column('clicks', sa.Integer(), nullable=False),
    sa.Column('cost_micros', sa.Integer(), nullable=False),
    sa.Column('conversions', sa.Float(), nullable=False),
    sa.Column('conversion_value', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ads_campaign_daily_date'), 'ads_campaign_daily', ['date'], unique=False)
    op.create_index(op.f('ix_ads_campaign_daily_project_id'), 'ads_campaign_daily', ['project_id'], unique=False)
    op.create_index('ix_ads_campaign_project_date', 'ads_campaign_daily', ['project_id', 'date'], unique=False)
    op.create_table('ads_keyword_daily',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('campaign_id', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('ad_group_id', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('criterion_id', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('keyword_text', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('match_type', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('impressions', sa.Integer(), nullable=False),
    sa.Column('clicks', sa.Integer(), nullable=False),
    sa.Column('cost_micros', sa.Integer(), nullable=False),
    sa.Column('conversions', sa.Float(), nullable=False),
    sa.Column('average_cpc_micros', sa.Integer(), nullable=False),
    sa.Column('quality_score', sa.Integer(), nullable=True),
    sa.Column('final_url', sqlmodel.sql.sqltypes.AutoString(length=2048), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ads_keyword_daily_date'), 'ads_keyword_daily', ['date'], unique=False)
    op.create_index(op.f('ix_ads_keyword_daily_keyword_text'), 'ads_keyword_daily', ['keyword_text'], unique=False)
    op.create_index(op.f('ix_ads_keyword_daily_project_id'), 'ads_keyword_daily', ['project_id'], unique=False)
    op.create_index('ix_ads_keyword_project_date', 'ads_keyword_daily', ['project_id', 'date'], unique=False)
    op.create_table('traffic_daily',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('source_key', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('sessions', sa.Integer(), nullable=True),
    sa.Column('users', sa.Integer(), nullable=True),
    sa.Column('pageviews', sa.Integer(), nullable=True),
    sa.Column('bounce_rate', sa.Float(), nullable=True),
    sa.Column('avg_session_duration', sa.Float(), nullable=True),
    sa.Column('clicks', sa.Integer(), nullable=True),
    sa.Column('impressions', sa.Integer(), nullable=True),
    sa.Column('lcp_p75', sa.Float(), nullable=True),
    sa.Column('fid_p75', sa.Float(), nullable=True),
    sa.Column('cls_p75', sa.Float(), nullable=True),
    sa.Column('dimensions_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_traffic_daily_date'), 'traffic_daily', ['date'], unique=False)
    op.create_index(op.f('ix_traffic_daily_project_id'), 'traffic_daily', ['project_id'], unique=False)
    op.create_index('ix_traffic_project_date_source', 'traffic_daily', ['project_id', 'date', 'source_key'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_traffic_project_date_source', table_name='traffic_daily')
    op.drop_index(op.f('ix_traffic_daily_project_id'), table_name='traffic_daily')
    op.drop_index(op.f('ix_traffic_daily_date'), table_name='traffic_daily')
    op.drop_table('traffic_daily')
    op.drop_index('ix_ads_keyword_project_date', table_name='ads_keyword_daily')
    op.drop_index(op.f('ix_ads_keyword_daily_project_id'), table_name='ads_keyword_daily')
    op.drop_index(op.f('ix_ads_keyword_daily_keyword_text'), table_name='ads_keyword_daily')
    op.drop_index(op.f('ix_ads_keyword_daily_date'), table_name='ads_keyword_daily')
    op.drop_table('ads_keyword_daily')
    op.drop_index('ix_ads_campaign_project_date', table_name='ads_campaign_daily')
    op.drop_index(op.f('ix_ads_campaign_daily_project_id'), table_name='ads_campaign_daily')
    op.drop_index(op.f('ix_ads_campaign_daily_date'), table_name='ads_campaign_daily')
    op.drop_table('ads_campaign_daily')
    op.drop_index(op.f('ix_ads_accounts_project_id'), table_name='ads_accounts')
    op.drop_table('ads_accounts')
    op.drop_index(op.f('ix_transparency_creatives_advertiser_id'), table_name='transparency_creatives')
    op.drop_index('ix_transparency_advertiser', table_name='transparency_creatives')
    op.drop_table('transparency_creatives')
    # ### end Alembic commands ###
