"""Add cascade delete to job_runs foreign keys

Revision ID: a7181391766e
Revises: 3f4825412d10
Create Date: 2025-12-23 17:44:15.899259

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'a7181391766e'
down_revision = '3f4825412d10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('job_runs_project_id_fkey'), 'job_runs', type_='foreignkey')
    op.drop_constraint(op.f('job_runs_user_id_fkey'), 'job_runs', type_='foreignkey')
    op.create_foreign_key(None, 'job_runs', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'job_runs', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'job_runs', type_='foreignkey')
    op.drop_constraint(None, 'job_runs', type_='foreignkey')
    op.create_foreign_key(op.f('job_runs_user_id_fkey'), 'job_runs', 'user', ['user_id'], ['id'])
    op.create_foreign_key(op.f('job_runs_project_id_fkey'), 'job_runs', 'projects', ['project_id'], ['id'])
    # ### end Alembic commands ###
