"""Add GSC tables

Revision ID: a8ea415ad0f1
Revises: 77044cb88c57
Create Date: 2025-12-23 18:47:01.121875

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'a8ea415ad0f1'
down_revision = '77044cb88c57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gsc_page_daily',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('page', sqlmodel.sql.sqltypes.AutoString(length=2048), nullable=False),
    sa.Column('country', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True),
    sa.Column('device', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('clicks', sa.Integer(), nullable=False),
    sa.Column('impressions', sa.Integer(), nullable=False),
    sa.Column('ctr', sa.Float(), nullable=False),
    sa.Column('position', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gsc_page_daily_date'), 'gsc_page_daily', ['date'], unique=False)
    op.create_index(op.f('ix_gsc_page_daily_project_id'), 'gsc_page_daily', ['project_id'], unique=False)
    op.create_table('gsc_properties',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('site_url', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=False),
    sa.Column('permission_level', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('linked_at', sa.DateTime(), nullable=False),
    sa.Column('last_sync_at', sa.DateTime(), nullable=True),
    sa.Column('sync_status', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('sync_error', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=True),
    sa.Column('search_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gsc_properties_project_id'), 'gsc_properties', ['project_id'], unique=True)
    op.create_table('gsc_query_daily',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('query', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=False),
    sa.Column('page', sqlmodel.sql.sqltypes.AutoString(length=2048), nullable=True),
    sa.Column('country', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True),
    sa.Column('device', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('clicks', sa.Integer(), nullable=False),
    sa.Column('impressions', sa.Integer(), nullable=False),
    sa.Column('ctr', sa.Float(), nullable=False),
    sa.Column('position', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gsc_query_daily_date'), 'gsc_query_daily', ['date'], unique=False)
    op.create_index(op.f('ix_gsc_query_daily_project_id'), 'gsc_query_daily', ['project_id'], unique=False)
    op.create_index(op.f('ix_gsc_query_daily_query'), 'gsc_query_daily', ['query'], unique=False)
    op.create_table('keyword_clusters',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('label', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('algorithm', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('total_clicks', sa.Integer(), nullable=False),
    sa.Column('total_impressions', sa.Integer(), nullable=False),
    sa.Column('avg_position', sa.Float(), nullable=False),
    sa.Column('query_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_keyword_clusters_project_id'), 'keyword_clusters', ['project_id'], unique=False)
    op.create_table('keyword_cluster_members',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('cluster_id', sa.Uuid(), nullable=False),
    sa.Column('query', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], ['keyword_clusters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_keyword_cluster_members_cluster_id'), 'keyword_cluster_members', ['cluster_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_keyword_cluster_members_cluster_id'), table_name='keyword_cluster_members')
    op.drop_table('keyword_cluster_members')
    op.drop_index(op.f('ix_keyword_clusters_project_id'), table_name='keyword_clusters')
    op.drop_table('keyword_clusters')
    op.drop_index(op.f('ix_gsc_query_daily_query'), table_name='gsc_query_daily')
    op.drop_index(op.f('ix_gsc_query_daily_project_id'), table_name='gsc_query_daily')
    op.drop_index(op.f('ix_gsc_query_daily_date'), table_name='gsc_query_daily')
    op.drop_table('gsc_query_daily')
    op.drop_index(op.f('ix_gsc_properties_project_id'), table_name='gsc_properties')
    op.drop_table('gsc_properties')
    op.drop_index(op.f('ix_gsc_page_daily_project_id'), table_name='gsc_page_daily')
    op.drop_index(op.f('ix_gsc_page_daily_date'), table_name='gsc_page_daily')
    op.drop_table('gsc_page_daily')
    # ### end Alembic commands ###
