"""add_links_tables_for_backlinks

Revision ID: b6b47410d782
Revises: 5c5f8a3724c8
Create Date: 2025-12-23 23:18:15.750898

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'b6b47410d782'
down_revision = '5c5f8a3724c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('link_snapshots',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('crawl_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('subset_spec', sa.JSON(), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('edges_count', sa.Integer(), nullable=False),
    sa.Column('domains_count', sa.Integer(), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('anchor_agg',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('snapshot_id', sa.Uuid(), nullable=False),
    sa.Column('target_domain', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('anchor_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('backlinks_count', sa.Integer(), nullable=False),
    sa.Column('ref_domains_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['snapshot_id'], ['link_snapshots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_anchor_agg_target_domain'), 'anchor_agg', ['target_domain'], unique=False)
    op.create_index('ix_anchor_target_domain', 'anchor_agg', ['target_domain'], unique=False)
    op.create_table('backlink_edges',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('snapshot_id', sa.Uuid(), nullable=False),
    sa.Column('source_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('target_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_domain', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('target_domain', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('anchor_text', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_nofollow', sa.Boolean(), nullable=False),
    sa.Column('is_sponsored', sa.Boolean(), nullable=False),
    sa.Column('is_ugc', sa.Boolean(), nullable=False),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['snapshot_id'], ['link_snapshots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_backlink_edges_source_domain'), 'backlink_edges', ['source_domain'], unique=False)
    op.create_index(op.f('ix_backlink_edges_target_domain'), 'backlink_edges', ['target_domain'], unique=False)
    op.create_index('ix_backlink_snapshot', 'backlink_edges', ['snapshot_id'], unique=False)
    op.create_index('ix_backlink_source_domain', 'backlink_edges', ['source_domain'], unique=False)
    op.create_index('ix_backlink_target_domain', 'backlink_edges', ['target_domain'], unique=False)
    op.create_table('ref_domain_agg',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('snapshot_id', sa.Uuid(), nullable=False),
    sa.Column('target_domain', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ref_domain', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('backlinks_count', sa.Integer(), nullable=False),
    sa.Column('dofollow_count', sa.Integer(), nullable=False),
    sa.Column('nofollow_count', sa.Integer(), nullable=False),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('top_anchors', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['snapshot_id'], ['link_snapshots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ref_domain_agg_ref_domain'), 'ref_domain_agg', ['ref_domain'], unique=False)
    op.create_index(op.f('ix_ref_domain_agg_target_domain'), 'ref_domain_agg', ['target_domain'], unique=False)
    op.create_index('ix_ref_domain_ref', 'ref_domain_agg', ['ref_domain'], unique=False)
    op.create_index('ix_ref_domain_target', 'ref_domain_agg', ['target_domain'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ref_domain_target', table_name='ref_domain_agg')
    op.drop_index('ix_ref_domain_ref', table_name='ref_domain_agg')
    op.drop_index(op.f('ix_ref_domain_agg_target_domain'), table_name='ref_domain_agg')
    op.drop_index(op.f('ix_ref_domain_agg_ref_domain'), table_name='ref_domain_agg')
    op.drop_table('ref_domain_agg')
    op.drop_index('ix_backlink_target_domain', table_name='backlink_edges')
    op.drop_index('ix_backlink_source_domain', table_name='backlink_edges')
    op.drop_index('ix_backlink_snapshot', table_name='backlink_edges')
    op.drop_index(op.f('ix_backlink_edges_target_domain'), table_name='backlink_edges')
    op.drop_index(op.f('ix_backlink_edges_source_domain'), table_name='backlink_edges')
    op.drop_table('backlink_edges')
    op.drop_index('ix_anchor_target_domain', table_name='anchor_agg')
    op.drop_index(op.f('ix_anchor_agg_target_domain'), table_name='anchor_agg')
    op.drop_table('anchor_agg')
    op.drop_table('link_snapshots')
    # ### end Alembic commands ###
